; LLVM IR generated by Triangle compiler
; Source: E:\U\COMPUTACION\COMPUTACION SEMESTRE VI\Compiladores e Interpretes\Triangle-Package-Impl\test.tri

target triple = "x86_64-pc-windows-msvc"
target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

@.str_int = private unnamed_addr constant [3 x i8] c"%d\00", align 1
@.str_int_space = private unnamed_addr constant [4 x i8] c"%d \00", align 1
@.str_char = private unnamed_addr constant [3 x i8] c"%c\00", align 1
@.str_scan_int = private unnamed_addr constant [3 x i8] c"%d\00", align 1
@.str_scan_char = private unnamed_addr constant [4 x i8] c" %c\00", align 1
declare i32 @printf(ptr, ...) #0
declare i32 @putchar(i32) #0

attributes #0 = { nounwind }


; ==================== MAIN ====================

define dso_local i32 @main() {
entry:
  %x = alloca i32, align 4
  store i32 0, ptr %x, align 4
  %y = alloca i32, align 4
  store i32 0, ptr %y, align 4
  store i32 10, ptr %x, align 4
  store i32 20, ptr %y, align 4
  %tmp0 = load i32, ptr %x, align 4
  %tmp1 = load i32, ptr %y, align 4
  %tmp2 = add nsw i32 %tmp0, %tmp1
  call i32 (ptr, ...) @printf(ptr @.str_int, i32 %tmp2)
  call i32 @putchar(i32 10)
  ret i32 0
}
