package Triangle.LLVMCodeGenerator;

import java.util.*;

/**
 * Representa un módulo completo de LLVM
 * Un módulo contiene funciones, variables globales, declaraciones y metadatos
 */
public class LLVMModule {
    private final String name;
    private final List<LLVMFunction> functions;
    private final List<String> globalVariables;
    private final List<String> declarations;
    private final List<String> typeDefinitions;
    private final List<String> metadata;
    private String targetTriple;
    private String dataLayout;
    
    public LLVMModule(String name) {
        this.name = name;
        this.functions = new ArrayList<>();
        this.globalVariables = new ArrayList<>();
        this.declarations = new ArrayList<>();
        this.typeDefinitions = new ArrayList<>();
        this.metadata = new ArrayList<>();
        
        // Valores por defecto para Windows x64
        this.targetTriple = "x86_64-pc-windows-msvc";
        this.dataLayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128";
    }
    
    /**
     * Obtiene el nombre del módulo
     */
    public String getName() {
        return name;
    }
    
    /**
     * Establece el target triple
     */
    public void setTargetTriple(String triple) {
        this.targetTriple = triple;
    }
    
    /**
     * Establece el data layout
     */
    public void setDataLayout(String layout) {
        this.dataLayout = layout;
    }
    
    /**
     * Añade una función al módulo
     */
    public void addFunction(LLVMFunction function) {
        functions.add(function);
    }
    
    /**
     * Añade una variable global
     */
    public void addGlobalVariable(String global) {
        globalVariables.add(global);
    }
    
    /**
     * Añade una declaración de función externa
     */
    public void addDeclaration(String declaration) {
        declarations.add(declaration);
    }
    
    /**
     * Añade una declaración usando una función
     */
    public void addDeclaration(LLVMFunction function) {
        if (!function.isDeclaration()) {
            throw new IllegalArgumentException("Function must be a declaration");
        }
        declarations.add(function.toIR());
    }
    
    /**
     * Añade una definición de tipo
     */
    public void addTypeDefinition(String typeDef) {
        typeDefinitions.add(typeDef);
    }
    
    /**
     * Añade metadatos
     */
    public void addMetadata(String meta) {
        metadata.add(meta);
    }
    
    /**
     * Obtiene todas las funciones
     */
    public List<LLVMFunction> getFunctions() {
        return new ArrayList<>(functions);
    }
    
    /**
     * Busca una función por nombre
     */
    public LLVMFunction getFunction(String name) {
        for (LLVMFunction func : functions) {
            if (func.getName().equals(name)) {
                return func;
            }
        }
        return null;
    }
    
    /**
     * Añade declaraciones estándar comunes (printf, scanf, etc.)
     */
    public void addStandardDeclarations() {
        // printf
        LLVMFunction printf = new LLVMFunction.Builder("printf")
            .returnType(LLVMType.i32())
            .addParameter("format", LLVMType.ptr(LLVMType.i8()))
            .declaration()
            .build();
        addDeclaration(printf);
        
        // putchar
        LLVMFunction putchar = new LLVMFunction.Builder("putchar")
            .returnType(LLVMType.i32())
            .addParameter("c", LLVMType.i32())
            .declaration()
            .build();
        addDeclaration(putchar);
        
        // getchar
        LLVMFunction getchar = new LLVMFunction.Builder("getchar")
            .returnType(LLVMType.i32())
            .declaration()
            .build();
        addDeclaration(getchar);
        
        // malloc
        LLVMFunction malloc = new LLVMFunction.Builder("malloc")
            .returnType(LLVMType.ptr(LLVMType.i8()))
            .addParameter("size", LLVMType.i64())
            .declaration()
            .build();
        addDeclaration(malloc);
        
        // free
        LLVMFunction free = new LLVMFunction.Builder("free")
            .returnType(LLVMType.voidType())
            .addParameter("ptr", LLVMType.ptr(LLVMType.i8()))
            .declaration()
            .build();
        addDeclaration(free);
    }
    
    /**
     * Genera el código LLVM IR completo del módulo
     */
    public String toIR() {
        StringBuilder sb = new StringBuilder();
        
        // Comentario de header
        sb.append("; Module: ").append(name).append("\n");
        sb.append("; Generated by Triangle Compiler - LLVM Code Generator\n\n");
        
        // Target information
        if (targetTriple != null && !targetTriple.isEmpty()) {
            sb.append("target triple = \"").append(targetTriple).append("\"\n");
        }
        
        if (dataLayout != null && !dataLayout.isEmpty()) {
            sb.append("target datalayout = \"").append(dataLayout).append("\"\n");
        }
        
        sb.append("\n");
        
        // Type definitions
        if (!typeDefinitions.isEmpty()) {
            sb.append("; Type Definitions\n");
            for (String typeDef : typeDefinitions) {
                sb.append(typeDef).append("\n");
            }
            sb.append("\n");
        }
        
        // Global variables
        if (!globalVariables.isEmpty()) {
            sb.append("; Global Variables\n");
            for (String global : globalVariables) {
                sb.append(global).append("\n");
            }
            sb.append("\n");
        }
        
        // External declarations
        if (!declarations.isEmpty()) {
            sb.append("; External Function Declarations\n");
            for (String declaration : declarations) {
                sb.append(declaration).append("\n");
            }
            sb.append("\n");
        }
        
        // Functions
        if (!functions.isEmpty()) {
            sb.append("; Function Definitions\n");
            for (LLVMFunction function : functions) {
                sb.append(function.toIR()).append("\n\n");
            }
        }
        
        // Metadata
        if (!metadata.isEmpty()) {
            sb.append("; Metadata\n");
            for (String meta : metadata) {
                sb.append(meta).append("\n");
            }
        }
        
        return sb.toString();
    }
    
    /**
     * Guarda el módulo a un archivo
     */
    public void saveToFile(String filename) throws java.io.IOException {
        java.nio.file.Files.write(
            java.nio.file.Paths.get(filename),
            toIR().getBytes(java.nio.charset.StandardCharsets.UTF_8)
        );
    }
    
    /**
     * Builder para módulos
     */
    public static class Builder {
        private String name;
        private String targetTriple;
        private String dataLayout;
        private boolean includeStandardDeclarations = true;
        
        public Builder(String name) {
            this.name = name;
        }
        
        public Builder targetTriple(String triple) {
            this.targetTriple = triple;
            return this;
        }
        
        public Builder dataLayout(String layout) {
            this.dataLayout = layout;
            return this;
        }
        
        public Builder withStandardDeclarations(boolean include) {
            this.includeStandardDeclarations = include;
            return this;
        }
        
        public LLVMModule build() {
            LLVMModule module = new LLVMModule(name);
            
            if (targetTriple != null) {
                module.setTargetTriple(targetTriple);
            }
            
            if (dataLayout != null) {
                module.setDataLayout(dataLayout);
            }
            
            if (includeStandardDeclarations) {
                module.addStandardDeclarations();
            }
            
            return module;
        }
    }
    
    @Override
    public String toString() {
        return "Module{" + name + ", " + functions.size() + " functions, " + 
               globalVariables.size() + " globals}";
    }
}
